CREATE TABLE users (
  handle varchar(20) NOT NULL default '',
  password varchar(64) default NULL,
  name varchar(100) default NULL,
  email varchar(100) default NULL,
  homepage varchar(255) default NULL,
  created datetime default NULL,
  createdby varchar(20) default NULL,
  lastlogin datetime default NULL,
  showemail tinyint(1) default NULL,
  registered tinyint(1) default NULL,
  admin tinyint(1) default NULL,
  userinfo varchar(255) default NULL,
  pgpkeyid varchar(20) default NULL,
  pgpkey text,
  wishlist varchar(255) NOT NULL default '',
  PRIMARY KEY  (handle),
  KEY handle (handle,registered),
  KEY pgpkeyid (pgpkeyid)
);
