CREATE TABLE users (
  handle varchar(20) NOT NULL default '',
  password varchar(64) default NULL,
  name varchar(100) default NULL,
  email varchar(100) default NULL,
  homepage varchar(255) default NULL,
  created datetime default NULL,
  createdby varchar(20) default NULL,
  lastlogin datetime default NULL,
  showemail tinyint(1) default NULL,
  registered tinyint(1) default NULL,
  admin tinyint(1) default NULL,
  userinfo text,
  pgpkeyid varchar(20) default NULL,
  pgpkey text,
  wishlist varchar(255) NOT NULL default '',
  birthdate date default NULL,
  locale varchar(30) default NULL,
  timezone varchar(20) default NULL,
  occupation varchar(255) default NULL,
  currentjob varchar(255) default NULL,
  available tinyint(1) default NULL,
  certified enum('no','PHP 4','PHP 5') NOT NULL default 'no',
  otherquals text,
  spokenlangs text,
  programlangs text,
  otherphpnet text,
  otheross text,
  otherhobbies text,
  anon tinyint(1) default NULL,
  PRIMARY KEY  (handle),
  KEY handle (handle,registered),
  KEY pgpkeyid (pgpkeyid)
);
